### ISSUE TITLE
How is this supposed to work? There's no output, no error message

### ISSUE THREAD

**Issue by mzso** [marselas/sgt2wav#1]
I tried `sgt2wav.exe SNEAK1.SGT`
Nothing happened. The help it shows is rather cryptic. There's something about an audio device, but no devices are listed.

<img width="509" height="394" alt="Image" src="https://github.com/user-attachments/assets/f73b0ca5-2f05-4244-ad66-2d1a8f4fe86f" />

Also, I wanted to convert some motifs from an sty file. But I guess that's not supported?

**Comment by marselas** [comment]
This requires Windows 7, Windows 8, Vista, or an early version of Windows 10. Later versions of Windows 10, and Windows 11, are not supported as Microsoft removed OS support for the underlying DirectMusic interface.  I've updated the readme.

**Comment by mzso** [comment]
@marselas 
Thanks for the reply. Isn't it possible to copy some dll-s to get it to work? Or is it more complicated?
A long time desire of mine is to convert the music of one of my favorite videogames (The Operative: No One Lives Forever) into high quality audio files. 


PS:
I'm guessing because of the same reason directmusic producer can't export to wav either. 

XP support is not listed. Is it certain the sgt2wav won't run on it? It would be easier to try both in one VM.

**Comment by mzso** [comment]
@marselas 
There's a [directmusic fix package](https://community.pcgamingwiki.com/files/file/3244-directmusic-fix/) on the pcgamingwiki.
The the instructions are very unclear though. And don't seem to match the package.

**Comment by mzso** [comment]
@marselas Well, I tried copying the dlls to the respective folders and runing the batch for the reg files, and regsrv32 for the dlls. But no change. It doesn't help that the program doesn't show any errors.
This is what I tried: `sgt2wav.exe -source:bumper4.sgt` Should this work? Or as long as no device is added it won't? (The help still shows an empty list for devices.)

**Comment by marselas** [comment]
DirectMusic doesn't work on newer versions of Windows due to the removal of
the OS integration.  There's no getting around it.  You could probably
successfully run it under Linux/Wine, but I haven't tried it
